version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py

python:
   install:
    - requirements: deeplake/requirements/docs.txt
    - method: pip
      path: .
