{% set name = "hub" %}
{% set version = "1.2.2" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  entry_points:
    - hub = hub.cli.command:cli
    - hub-local = hub.cli.local:cli
    - hub-dev = hub.cli.dev:cli
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - azure-storage-blob
    - boto3
    - cachey
    - click
    - cloudpickle
    - fsspec
    - gcsfs
    - lz4
    - msgpack-python
    - numpy
    - outdated
    - pathos
    - pillow
    - pip
    - psutil
    - python
    - requests
    - s3fs
    - tqdm
    - zarr
  run:
    - azure-storage-blob
    - boto3
    - cachey
    - click
    - cloudpickle
    - fsspec
    - gcsfs
    - lz4
    - msgpack-python
    - numpy
    - outdated
    - pathos
    - pillow
    - psutil
    - python
    - requests
    - s3fs
    - tqdm
    - zarr

test:
  imports:
    - hub
    - hub.api
    - hub.cli
    - hub.client
    - hub.codec
    - hub.collections
    - hub.collections.dataset
    - hub.collections.tensor
    - hub.compute
    - hub.schema
    - hub.store
    - hub.store.tests
  commands:
    - hub --help
    - hub-local --help
    - hub-dev --help
  requires:
    - mock >=1.0.1
    - pytest

about:
  home: "https://github.com/activeloopai/Hub"
  license: "Mozilla Public 2.0 (MPL 2.0)"
  license_family: MOZILLA
  license_file: 
  summary: "Activeloop Hub"
  doc_url: "https://docs.activeloop.ai/en/latest/"
  dev_url: 

extra:
  recipe-maintainers:
    - haiyangdeperci
