include(ExternalProject)

if("${AL_SYSTEM}" STREQUAL "emscripten")
    message(STATUS "Skipping blas for emscripten")
elseif(UNIX AND NOT APPLE)
    if(EXISTS /opt/intel/oneapi/mkl/latest/)
        set(MKLROOT /opt/intel/oneapi/mkl/latest/)
        message(STATUS "MKL found using it as blas implementation.")
        include_directories(/opt/intel/oneapi/mkl/latest/include/)
        include_directories(${CMAKE_CURRENT_SOURCE_DIR}/3rd_party/cblas/)
        set(BLAS_LIBRARIES
            "-Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_ilp64.a ${MKLROOT}/lib/intel64/libmkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl"
        )
        set(BLAS_COMPILE_OPTIONS "-DMKL_ILP64  -m64 -I${MKLROOT}/include -DHAVE_BLAS")
    endif()
elseif(APPLE)
    find_library(ACCELERATE Accelerate)
    include_directories(${ACCELERATE}/Frameworks/vecLib.framework/Headers/)
    set(BLAS_LIBRARIES "-framework Accelerate")
    set(BLAS_COMPILE_OPTIONS "-I${ACCELERATE}/Frameworks/vecLib.framework/Headers/ -DHAVE_BLAS")
endif()
