// DeepLake API Build Configuration
// This file is automatically generated during build - DO NOT EDIT
// Generated from config.hpp.in

#pragma once

// Version Information
#define DEEPLAKE_VERSION_MAJOR 4
#define DEEPLAKE_VERSION_MINOR 4
#define DEEPLAKE_VERSION_PATCH 4
#define DEEPLAKE_VERSION "4.4.4"

// Build Configuration Flags
/* #undef AL_DEBUG */
/* #undef AL_ASSERTIONS */

// Build Information
#define AL_PRESET_NAME "deeplake-api-prod"
#define CMAKE_BUILD_TYPE "RelWithDebInfo"

// Platform Detection
#if defined(_WIN32) || defined(_WIN64)
    #define PLATFORM_WINDOWS
#elif defined(__APPLE__) && defined(__MACH__)
    #define PLATFORM_MACOS
#elif defined(__linux__)
    #define PLATFORM_LINUX
#elif defined(__unix__)
    #define PLATFORM_UNIX
#endif

// Compiler Detection
#if defined(__clang__)
    #define COMPILER_CLANG
    #define COMPILER_VERSION __clang_major__ * 100 + __clang_minor__
#elif defined(__GNUC__) || defined(__GNUG__)
    #define COMPILER_GCC
    #define COMPILER_VERSION __GNUC__ * 100 + __GNUC_MINOR__
#elif defined(_MSC_VER)
    #define COMPILER_MSVC
    #define COMPILER_VERSION _MSC_VER
#endif

// C++ Standard Detection
#if __cplusplus >= 202002L
    #define CPP_STANDARD 20
#elif __cplusplus >= 201703L
    #define CPP_STANDARD 17
#elif __cplusplus >= 201402L
    #define CPP_STANDARD 14
#else
    #define CPP_STANDARD 11
#endif

// Build Type Helpers
#ifdef AL_DEBUG
    #define IS_DEBUG_BUILD 1
    #define IS_RELEASE_BUILD 0
#else
    #define IS_DEBUG_BUILD 0
    #define IS_RELEASE_BUILD 1
#endif

#ifdef AL_ASSERTIONS
    #define ASSERTIONS_ENABLED 1
#else
    #define ASSERTIONS_ENABLED 0
#endif

// Version Comparison Macro
#define DEEPLAKE_VERSION_CHECK(major, minor, patch) \
    ((DEEPLAKE_VERSION_MAJOR > (major)) || \
     (DEEPLAKE_VERSION_MAJOR == (major) && DEEPLAKE_VERSION_MINOR > (minor)) || \
     (DEEPLAKE_VERSION_MAJOR == (major) && DEEPLAKE_VERSION_MINOR == (minor) && DEEPLAKE_VERSION_PATCH >= (patch)))
