name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels:
  - enhancement
body:

  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of what could be improved. 
        - If your feature request is related to a problem, link any relevant issues.
        - Include possible solution(s) you have considered. Add any drawbacks you thought of.
        - Ensure private information is redacted
        
        If you can, explain how users will be able to use this and possibly write out a version the docs.
        - Maybe a screenshot or design?
    validations:
      required: true
