
   
"""Adds repositories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/eventuals-grpc-examples repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of eventuals-grpc-examples follow the Bazel build
# instructions at https://github.com/3rdparty/eventuals-grpc-example.
########################################################################

load("//3rdparty/eventuals:repos.bzl", eventuals_grpc_repos = "repos")

def repos(external = True, repo_mapping = {}):
    eventuals_grpc_repos(
        repo_mapping = repo_mapping,
    )