name: Add pr-ready label
on:
  workflow_run:
    workflows: ["PR Automated Tests"]
    types:
      - completed
jobs:
  pr-ready:
    name: Add pr-ready label
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact from PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ACTIVELOOP_BOT_PAT }}
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      - run: unzip pr.zip
      - name: Add pr-ready label
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ACTIVELOOP_BOT_PAT }}
          script: |
            var fs = require('fs');
            var issue_number = Number(fs.readFileSync('./NR'));
            await github.issues.addLabel({
              issue_number,
              owner: 'activeloopai',
              repo: 'hub',
              name: 'pr-ready'
            });