name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    if: github.repository == 'activeloopai/deeplake'
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
