# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.jsonxw
name: PR Automated Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs if available
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
  test-pr:
    uses: activeloopai/shared-github-actions/.github/workflows/local_test.yml@main
    with:
      repo: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.sha }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  add-artifacts:
    name: Save PR number for the workflow run trigger
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR Number file
        if: always()
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - name: Uploading to GitHub
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: pr
          path: pr/